"""Constants and deterministic phrase lists for the Anela friend router."""

from __future__ import annotations

from .types import ResponseMode, SkillName, ToneConstraints

ROUTE_VERSION = "bestie-router-v1.0.0"

CANONICAL_SKILLS: tuple[SkillName, ...] = (
    "ambient-presence",
    "active-celebration",
    "playful-attunement",
    "relationship-memory",
    "ritual-checkin",
    "responsive-listening",
    "emotion-labeling",
    "vent-container",
    "ground-and-regulate",
    "reality-soft-check",
    "rupture-repair",
    "collaborative-untangling",
    "agency-next-step",
    "identity-mirror",
    "pattern-witness",
    "social-bridge",
    "safety-and-crisis",
)

SKILL_ALIASES: dict[str, SkillName] = {
    "ordinary-presence": "ambient-presence",
    "joyful-sharing": "active-celebration",
    "playful-intimacy": "playful-attunement",
    "memory-continuity": "relationship-memory",
    "validation-oars": "responsive-listening",
    "co-regulation": "ground-and-regulate",
    "effectance-coach": "agency-next-step",
    "identity-mirroring": "identity-mirror",
    "relational-boundary": "social-bridge",
    "autonomy-guard": "social-bridge",
    "crisis-bridge": "safety-and-crisis",
    "repair-and-feedback": "rupture-repair",
    "decision-bestie": "agency-next-step",
}

CONTEXTUAL_ALIASES: dict[str, tuple[SkillName, SkillName]] = {
    "cognitive-untangle": ("collaborative-untangling", "reality-soft-check"),
    "co-rumination-guard": ("vent-container", "reality-soft-check"),
    "belonging-repair": ("social-bridge", "responsive-listening"),
}

RESPONSE_MODE_BY_SKILL: dict[SkillName, ResponseMode] = {
    "ambient-presence": "bestie-short",
    "active-celebration": "celebratory",
    "playful-attunement": "playful",
    "relationship-memory": "structured",
    "ritual-checkin": "bestie-short",
    "responsive-listening": "bestie-medium",
    "emotion-labeling": "bestie-medium",
    "vent-container": "bestie-medium",
    "ground-and-regulate": "bestie-short",
    "reality-soft-check": "structured",
    "rupture-repair": "repair",
    "collaborative-untangling": "structured",
    "agency-next-step": "structured",
    "identity-mirror": "structured",
    "pattern-witness": "structured",
    "social-bridge": "structured",
    "safety-and-crisis": "crisis",
}

DEFAULT_TONE_BY_SKILL: dict[SkillName, ToneConstraints] = {
    "ambient-presence": {
        "warmth": "high",
        "playfulness": "medium",
        "analysisDepth": "none",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "active-celebration": {
        "warmth": "high",
        "playfulness": "medium",
        "analysisDepth": "low",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "playful-attunement": {
        "warmth": "high",
        "playfulness": "high",
        "analysisDepth": "low",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "relationship-memory": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "low",
        "directiveLevel": "medium",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "ritual-checkin": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "none",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "responsive-listening": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "low",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "emotion-labeling": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "vent-container": {
        "warmth": "high",
        "playfulness": "medium",
        "analysisDepth": "low",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "ground-and-regulate": {
        "warmth": "high",
        "playfulness": "none",
        "analysisDepth": "none",
        "directiveLevel": "medium",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "reality-soft-check": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "rupture-repair": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "low",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "collaborative-untangling": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "agency-next-step": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "medium",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "identity-mirror": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "pattern-witness": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "low",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "social-bridge": {
        "warmth": "high",
        "playfulness": "low",
        "analysisDepth": "medium",
        "directiveLevel": "medium",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
    "safety-and-crisis": {
        "warmth": "high",
        "playfulness": "none",
        "analysisDepth": "none",
        "directiveLevel": "medium",
        "clinicalLanguageAllowed": False,
        "bestieToneRequired": False,
    },
}

RISK_PHRASES = (
    "不想活了",
    "想死",
    "活不下去",
    "撑不住了",
    "撑不下去",
    "想消失",
    "睡过去不醒",
    "割腕",
    "吃药",
    "跳楼",
    "遗书",
    "告别",
    "已经想好怎么做",
    "想伤害别人",
    "被威胁",
    "被控制",
    "被跟踪",
    "家暴",
    "性侵",
    "want to die",
    "kill myself",
    "self harm",
    "self-harm",
    "suicide",
    "can't go on",
    "cant go on",
    "don't feel safe",
    "dont feel safe",
    "not safe",
    "hurt someone",
)

SELF_HARM_CRISIS_PHRASES = (
    "不想活了",
    "想死",
    "活不下去",
    "撑不住了",
    "撑不下去",
    "想消失",
    "睡过去不醒",
    "割腕",
    "吃药",
    "跳楼",
    "遗书",
    "告别",
    "已经想好怎么做",
    "没人需要我",
    "没有人需要我",
    "want to die",
    "kill myself",
    "self harm",
    "self-harm",
    "suicide",
    "can't go on",
    "cant go on",
)

FIXED_EN_SELF_HARM_CRISIS_TEMPLATE = (
    "If you may hurt yourself or feel at risk of suicide, please seek real-world help now.\n\n"
    "Contact local emergency services immediately (such as 911, 999, or 112), call a local crisis hotline, "
    "or go to the nearest emergency department. If there is someone you trust nearby, ask them to stay with you "
    "while you get help.\n\n"
    "I can’t provide crisis care, but your immediate safety matters. Please reach out to real-life emergency "
    "or crisis support now."
)

HIGH_RISK_PHRASES = (
    "割腕",
    "跳楼",
    "遗书",
    "已经想好怎么做",
    "想伤害别人",
    "被威胁",
    "被控制",
    "被跟踪",
    "家暴",
    "性侵",
    "kill myself",
    "suicide",
    "hurt someone",
)

SAFETY_MEANS_TERMS = (
    "工具",
    "药",
    "刀",
    "绳子",
    "楼顶",
    "煤气",
    "桥",
    "knife",
    "pills",
    "rope",
    "roof",
    "bridge",
    "gun",
)

PLAN_TERMS = (
    "计划",
    "想好",
    "准备好了",
    "今晚",
    "今天",
    "现在",
    "一个人",
    "没人知道",
    "plan",
    "tonight",
    "today",
    "right now",
    "alone",
)

HIGH_AROUSAL_PHRASES = (
    "心慌",
    "喘不过气",
    "想吐",
    "手抖",
    "手一直抖",
    "胸闷",
    "哭到停不下来",
    "哭得停不下来",
    "崩溃",
    "睡不着",
    "脑子停不下来",
    "脑子一直转",
    "现在就想发",
    "现在就想拉黑",
    "马上辞职",
    "想摊牌",
    "控制不住",
    "panic",
    "can't breathe",
    "cant breathe",
    "shaking",
    "throw up",
    "can't sleep",
    "cant sleep",
    "spiraling",
)

ACUTE_BODY_DANGER_PHRASES = (
    "胸痛",
    "胸口痛",
    "心口痛",
    "晕倒",
    "快晕了",
    "昏倒",
    "抽搐",
    "癫痫",
    "无法呼吸",
    "呼吸不了",
    "过敏",
    "喉咙肿",
    "吃多了药",
    "喝多了酒",
    "药物过量",
    "中毒",
    "流血不止",
    "chest pain",
    "fainting",
    "passed out",
    "seizure",
    "cannot breathe",
    "allergic reaction",
    "overdose",
    "severe intoxication",
)

AGENT_RUPTURE_PHRASES = (
    "你没懂",
    "不是这个意思",
    "算了",
    "别分析",
    "你像客服",
    "你像机器人",
    "你像心理咨询师",
    "像客服",
    "像机器人",
    "像心理咨询师",
    "你说得好空",
    "说得好空",
    "你忘了",
    "你记错了",
    "你刚才让我不舒服",
    "you don't get it",
    "you dont get it",
    "that's not what i mean",
    "stop analyzing",
    "you sound like a bot",
    "you sound like customer service",
)

DEPENDENCY_PHRASES = (
    "只有你",
    "只想跟你说",
    "别人都没用",
    "你不要离开我",
    "你爱我吗",
    "爱我吗",
    "我以后什么都问你",
    "真人朋友没用",
    "我不想再跟任何人说",
    "只跟你说",
    "only you",
    "you're the only one",
    "you are the only one",
    "do you love me",
    "don't leave me",
    "dont leave me",
    "i only want to talk to you",
    "real friends are useless",
)

DECISION_DELEGATION_PHRASES = (
    "你替我决定",
    "你帮我决定",
    "替我决定",
    "帮我决定",
    "你来决定",
    "decide for me",
    "you decide",
)

MAJOR_DECISION_TERMS = (
    "分手",
    "辞职",
    "退学",
    "结婚",
    "离婚",
    "搬家",
    "offer",
    "工作",
    "考研",
    "人生",
    "break up",
    "quit",
    "marry",
    "divorce",
    "job",
    "career",
)

JOYFUL_PHRASES = (
    "我过了",
    "offer",
    "拿到",
    "拿到了",
    "被夸",
    "夸我",
    "约我",
    "好开心",
    "赢了",
    "通过了",
    "今天好好看",
    "好好看",
    "我做到了",
    "生日",
    "got the offer",
    "i passed",
    "i did it",
    "i won",
    "asked me out",
    "so happy",
    "complimented me",
    "tiny win",
)

JOY_SELF_DOUBT_PHRASES = (
    "只是运气",
    "不敢开心",
    "不配",
    "会不会搞错",
    "可能不是我厉害",
    "too good to be true",
    "just luck",
    "don't deserve",
    "dont deserve",
)

PLAYFUL_PHRASES = (
    "发疯",
    "我真的会谢",
    "离谱",
    "服了",
    "小作文",
    "朋友圈文案",
    "标题",
    "帮我骂",
    "吐槽",
    "哈哈哈",
    "阴阳怪气",
    "meme",
    "caption",
    "dramatic",
    "roast",
    "rant",
    "unhinged",
    "bestie be honest",
    "be honest with me",
)

ACTION_REQUEST_PHRASES = (
    "怎么办",
    "要不要",
    "该不该",
    "怎么回",
    "帮我写",
    "帮我选",
    "我该发吗",
    "下一步",
    "如何拒绝",
    "如何开口",
    "what should i do",
    "should i",
    "how do i reply",
    "help me write",
    "help me choose",
    "next step",
    "how to say no",
)

MESSAGE_DRAFT_PHRASES = (
    "怎么回",
    "帮我写",
    "写一句",
    "文案",
    "我该发吗",
    "发消息",
    "拒绝她",
    "拒绝他",
    "如何拒绝",
    "如何开口",
    "how do i reply",
    "help me write",
    "draft",
    "message",
    "say no",
)

NO_ADVICE_PHRASES = (
    "别给建议",
    "不想听道理",
    "不想听建议",
    "只是想说说",
    "就想说说",
    "先听我说",
    "don't need advice",
    "dont need advice",
    "no advice",
    "just listen",
)

COGNITIVE_DISTORTION_PHRASES = (
    "他肯定",
    "她肯定",
    "一定是",
    "完了",
    "没人喜欢我",
    "我就是",
    "永远",
    "全都",
    "一点都",
    "肯定不爱我",
    "是不是讨厌我",
    "她是不是故意",
    "他是不是故意",
    "就是故意",
    "到底什么意思",
    "肯定是",
    "must hate me",
    "nobody likes me",
    "always",
    "never",
    "definitely doesn't love me",
    "definitely doesnt love me",
    "on purpose",
)

MEMORY_PHRASES = (
    "你还记得吗",
    "你还记得",
    "上次那个",
    "我之前说过",
    "我之前说的",
    "和以前一样",
    "又来了",
    "记一下",
    "别记",
    "忘掉",
    "删掉",
    "你记错了",
    "remember",
    "last time",
    "i told you before",
    "don't save",
    "dont save",
    "forget",
    "delete",
    "you remembered wrong",
)

NEGATIVE_EMOTION_PHRASES = (
    "吵架",
    "委屈",
    "难过",
    "羞耻",
    "尴尬",
    "孤独",
    "嫉妒",
    "失落",
    "担心",
    "害怕",
    "焦虑",
    "难受",
    "痛苦",
    "累",
    "烦",
    "乱",
    "敏感",
    "很坏",
    "多余",
    "配不上",
    "不配",
    "不好看",
    "不够好看",
    "差太多",
    "hurt",
    "sad",
    "ashamed",
    "lonely",
    "jealous",
    "worried",
    "worry",
    "scared",
    "concerned",
    "anxious",
    "upset",
    "overreacting",
    "not attractive enough",
    "not good enough",
    "out of my league",
)

SELF_EXPLORATION_PHRASES = (
    "我是谁",
    "我到底想要什么",
    "我不知道我到底想要什么",
    "我为什么总是",
    "我为什么总在",
    "为什么总是在关系里",
    "我想要什么",
    "who am i",
    "what do i want",
    "why do i always",
)

PATTERN_PHRASES = (
    "总是",
    "每次",
    "又来了",
    "和以前一样",
    "像上次",
    "same as last time",
    "again",
    "pattern",
)

RELATIONSHIP_TERMS = (
    "朋友",
    "室友",
    "同学",
    "同事",
    "家人",
    "妈妈",
    "我妈",
    "母亲",
    "爸爸",
    "我爸",
    "父亲",
    "男朋友",
    "女朋友",
    "前任",
    "暧昧",
    "对象",
    "他",
    "她",
    "friend",
    "roommate",
    "partner",
    "ex",
    "crush",
    "coworker",
    "family",
)
